### ISSUE TITLE
Unix?

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/osx-learn#6]
I'm curious - is there any chance of there being a UNIX version of this that you know of?

**Comment by wooorm** [comment]
Hmmm, no clue, I don’t use non-osx unix, but def open for a PR doing just that!

**Comment by RichardLitt** [comment]
I think that would be better placed as being in a new module. Unfortunately, it's not for my machine, and I don't have a Unix box. But just checking for someone else. :) 

I'll close this as `wont-fix`.
