### ISSUE TITLE
"Not privileged to stop service."

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/osx-learn#7]
No idea what is going on here. 

```
Last login: Tue Apr  2 11:32:45 on ttys000
➜  ~ learn Gough
Not privileged to stop service.
➜  ~
```

**Comment by RichardLitt** [comment]
Sonoma 14.4.1 (23E224)

**Comment by wooorm** [comment]
oh no :(

Weird! No Clue!

**Comment by wooorm** [comment]
You can likely use `sudo` in front of it, then it works?

It could be that macOS is moving away from this file. Maybe they‘re doing AI stuff or so. 

Does `osx-learn`, with `sudo` still work with your other tools?

**Comment by RichardLitt** [comment]
Sudo appears to work. Maybe it's just a permissions thing. Hmm!

**Comment by wooorm** [comment]
it just happened for me too btw, on same OS. So it looks like apple changed something

**Comment by RichardLitt** [comment]
Might be worth noting in the docs?

**Comment by wooorm** [comment]
Lets check back in, in a month or so, to see if it's just a temporary apple bug or if there's some alternative! I'll set a reminder locally :)

**Comment by wooorm** [comment]
Looking some more into this, I think there are 2 things going on:

a) no longer allowed to stop/start/restart applespell, and many things
b) the dictionaries are now in a new location: `~/Library/Group Containers/group.com.apple.AppleSpell/Library/Spelling/` ([ref a](https://forum.affinity.serif.com/index.php?/topic/202141-spell-checking-and-sonoma-update-issue/), [ref b](https://apple.stackexchange.com/a/471699))

I’m not sure how to solve a). `rev b` also mentions the computer has to be restarted.
You should also notice b) yourself: all your local added terms aren‘t currently. Correct?
Could you see if you could move the old user dictionaries to the new location, and whether that works?

**Comment by RichardLitt** [comment]
`~/Library/Group\ Containers/group.com.apple.AppleSpell/` doesn't appear to be a directory. 

My local terms are currently working, but perhaps only on restart - adding words to ~/Library/Spelling/LocalDictionary doesn't work automatically. I'll see if it works on restart.

**Comment by RichardLitt** [comment]
My local terms are _not working_ apparently - Adding to `~/Library/Spelling/LocalDictionary` no longer seems to work. 

I can't write to ~/Library/Group Containers/group.com.apple.AppleSpell/Library/Spelling/, even with sudo.

**Comment by wooorm** [comment]
Are you sure you’re talking about `/Users/xxx/Group Containers/group.com.apple.AppleSpell/Library/Spelling/LocalDictionary`, and not the `/Libary/...` in root?
Can you see the `LocalDictionary` file though?

**Comment by RichardLitt** [comment]
Yes - even the one in my ~/Library. This is very annoying! 

I can't see it (can't `sudo ls`). I can try and vim into it, but I can't edit it, even with sudo.
